// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiuOO6yIbE1Db6w7xblH8NypkqSGNaqnw',
    appId: '1:1000597045919:web:71b97c3b18d085867d18aa',
    messagingSenderId: '1000597045919',
    projectId: 'chat-message-67482',
    authDomain: 'chat-message-67482.firebaseapp.com',
    storageBucket: 'chat-message-67482.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0QiqDO8KNgEg8hqgdzvPPSlCAEMcpbig',
    appId: '1:1000597045919:android:e685791b09f3d7f57d18aa',
    messagingSenderId: '1000597045919',
    projectId: 'chat-message-67482',
    storageBucket: 'chat-message-67482.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuKGo4f41bbUbSn2tZITeTl5v7iFFSvn8',
    appId: '1:1000597045919:ios:d5a47d128d296fdb7d18aa',
    messagingSenderId: '1000597045919',
    projectId: 'chat-message-67482',
    storageBucket: 'chat-message-67482.appspot.com',
    iosBundleId: 'com.example.flutterApplication5',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDuKGo4f41bbUbSn2tZITeTl5v7iFFSvn8',
    appId: '1:1000597045919:ios:d5a47d128d296fdb7d18aa',
    messagingSenderId: '1000597045919',
    projectId: 'chat-message-67482',
    storageBucket: 'chat-message-67482.appspot.com',
    iosBundleId: 'com.example.flutterApplication5',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCiuOO6yIbE1Db6w7xblH8NypkqSGNaqnw',
    appId: '1:1000597045919:web:6ff19216929374e97d18aa',
    messagingSenderId: '1000597045919',
    projectId: 'chat-message-67482',
    authDomain: 'chat-message-67482.firebaseapp.com',
    storageBucket: 'chat-message-67482.appspot.com',
  );
}
